/* SQLINES DEMO *** ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE BOMON
(
	MABM nvarchar(4) NOT NULL,
	TENBM nvarchar(40) NULL,
	PHONG nvarchar(3) NULL,
	DIENTHOAI nvarchar(12) NULL,
	TRUONGBM nvarchar(3) NULL,
	MAKHOA nvarchar(10) NULL,
	NGAYNHANCHUC date NULL,
	CONSTRAINT PK_BOMON PRIMARY KEY (MABM) 
);

/* SQLINES DEMO *** ******/
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE CHUDE
(
	MACD nvarchar(4) NOT NULL,
	TENCD nvarchar(50) NULL,
	CONSTRAINT PK_CHUDE PRIMARY KEY (MACD) 
);

/* SQLINES DEMO *** EC ******/
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE CONGVIEC
(
	MADT nvarchar(3) NOT NULL,
	SOTT int NOT NULL,
	TENCV nvarchar(50) NULL,
	NGAYBD date NULL,
	NGAYKT date NULL,
	CONSTRAINT PK_CONGVIEC PRIMARY KEY (MADT, SOTT) 
);

/* SQLINES DEMO *** ******/
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE DETAI
(
	MADT nvarchar(3) NOT NULL,
	TENDT nvarchar(50) NULL,
	CAPQL nvarchar(15) NULL,
	KINHPHI decimal(10, 1) NULL,
	NGAYBD date NULL,
	NGAYKT date NULL,
	MACD nvarchar(4) NULL,
	GVCNDT nvarchar(3) NULL,
	CONSTRAINT PK_DETAI PRIMARY KEY (MADT) 
);

/* SQLINES DEMO *** EN ******/
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE GIAOVIEN
(
	MAGV nvarchar(3) NOT NULL,
	HOTEN nvarchar(40) NULL,
	LUONG decimal(10, 1) NULL,
	PHAI nvarchar(3) NULL,
	NGSINH date NULL,
	DIACHI nvarchar(50) NULL,
	GVQLCM nvarchar(3) NULL,
	MABM nvarchar(4) NULL,
	CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV) 
);

/* SQLINES DEMO *** ******/
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE GV_DT
(
	MAGV nvarchar(3) NOT NULL,
	DIENTHOAI nvarchar(12) NOT NULL,
	CONSTRAINT PK_GV_DT PRIMARY KEY (MAGV, DIENTHOAI) 
);

/* SQLINES DEMO *** *****/
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE KHOA
(
	MAKHOA nvarchar(10) NOT NULL,
	TENKHOA nvarchar(40) NULL,
	NAMTL nvarchar(4) NULL,
	PHONG nvarchar(3) NULL,
	DIENTHOAI nvarchar(12) NULL,
	TRUONGKHOA nvarchar(3) NULL,
	NGAYNHANCHUC date NULL,
	CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA) 
);

/* SQLINES DEMO *** HAN ******/
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE NGUOITHAN
(
	MAGV nvarchar(3) NOT NULL,
	TEN nvarchar(15) NOT NULL,
	NGSINH date NULL,
	PHAI nvarchar(3) NULL,
	CONSTRAINT PK_NGUOITHAN PRIMARY KEY (MAGV, TEN) 
);

/* SQLINES DEMO *** ADT ******/
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE THAMGIADT
(
	MAGV nvarchar(3) NOT NULL,
	MADT nvarchar(3) NOT NULL,
	STT int NOT NULL,
	PHUCAP decimal(5, 1) NULL,
	KETQUA nvarchar(3) NULL,
	CONSTRAINT PK_THAMGIADT PRIMARY KEY (MAGV, MADT, STT) 
);

ALTER TABLE BOMON ADD CONSTRAINT FK_BOMON_GIAOVIEN FOREIGN KEY(TRUONGBM)
REFERENCES GIAOVIEN (MAGV);

ALTER TABLE BOMON ADD CONSTRAINT FK_BOMON_KHOA FOREIGN KEY(MAKHOA)
REFERENCES KHOA (MAKHOA);

ALTER TABLE CONGVIEC  ADD CONSTRAINT FK_CONGVIEC_DETAI FOREIGN KEY(MADT)
REFERENCES DETAI (MADT);

ALTER TABLE DETAI ADD CONSTRAINT FK_DETAI_CHUDE FOREIGN KEY(MACD)
REFERENCES CHUDE (MACD);

ALTER TABLE DETAI ADD CONSTRAINT FK_DETAI_GIAOVIEN FOREIGN KEY(GVCNDT)
REFERENCES GIAOVIEN (MAGV);

ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN_BOMON FOREIGN KEY(MABM)
REFERENCES BOMON (MABM);

ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN_GIAOVIEN FOREIGN KEY(GVQLCM)
REFERENCES GIAOVIEN (MAGV);

ALTER TABLE GV_DT  ADD CONSTRAINT FK_GV_DT_GIAOVIEN FOREIGN KEY(MAGV)
REFERENCES GIAOVIEN (MAGV);

ALTER TABLE KHOA ADD CONSTRAINT FK_KHOA_GIAOVIEN FOREIGN KEY(TRUONGKHOA)
REFERENCES GIAOVIEN (MAGV);

ALTER TABLE NGUOITHAN ADD CONSTRAINT FK_NGUOITHAN_GIAOVIEN FOREIGN KEY(MAGV)
REFERENCES GIAOVIEN (MAGV);

ALTER TABLE THAMGIADT ADD CONSTRAINT FK_THAMGIADT_CONGVIEC FOREIGN KEY(MADT, STT)
REFERENCES CONGVIEC (MADT, SOTT);

ALTER TABLE THAMGIADT ADD CONSTRAINT FK_THAMGIADT_GIAOVIEN FOREIGN KEY(MAGV)
REFERENCES GIAOVIEN (MAGV);